### PR TITLE
Add useWatchedState hook to monitor a piece of board state

### PR DESCRIPTION
**Pull request by MathieuLoutre**
Following from the discussion in #85, here's a first draft of a `useWatchedState` hook which allows to monitor a piece of state from the board props and get updates on it as soon as it changes. This can help stagger the release of the state to the client by having different effects release different pieces of state.

A few notes for discussion:
- I did my best with the types, but there are quite a few of them missing (as `any` right now) in the hook. I tried to understand what was going on in `useEffectListener` for the handlers etc. but I have to say I was completely thrown off by the syntax.
- A piece of state might be changed by a few effects, it might be nice to be able to use a list of effects rather than just one?
- The current implementation assumes a pure fonction which only relies on the board props. It's easier to manage dependencies like this. Is it worth changing the signature to allow external deps?
- This implementation completely disregards the payload and to be honest it feels a little odd. It did cross my mind that maybe the function that chooses a piece of the props might be better as part of the effect call inside the moves but then listening to multiple events wouldn't work. We might need a better way to be explicit about discarding the payload?
- I added a new context rather than piggy back on an existing one but that was to keep things tidy, happy to bundle if needed. Additionally it stores the current props maintained by the plugin rather than the "true" props received by the client (`bgioProps` and not `props`). When writing `useWatchedState` it occurred to me that if it were the latest props, the `useBoardProps` state could be used to get the props instead of using the state in the callback. That said, the state in the callback seems better to avoid unnecessary renders. However, maybe it would be interesting to store both "old" and "new" props in the context and let the user decide what to get? (and maybe 2 hooks instead of one to choose which one to get?)

### CODE REVIEW

**Comment by delucis** [comment]
Thanks for this @MathieuLoutre!

> I did my best with the types, but there are quite a few of them missing…

Completely understandable, we can improve the types once we have the final API nailed down.

> A piece of state might be changed by a few effects, it might be nice to be able to use a list of effects rather than just one?

This seems like a good idea. The first argument could be a string or a string array. The one caveat is that there would be a race condition with the `isActive` flag with overlapping effects. Do you think the `isActive` flag is actually important here or should that just belong in `useEffectState`? Perhaps this hook could return just the watched state if the main use case is consuming state in a fairly normal way but with more timing control? So:

```js
const G = useWatchedState('rollDie', ({ G }) => G);
```

An alternative might be to return a map of effect names to `isActive` states, like:

```js
const [state, isActive] = useWatchedState(['A', 'B'], ({ G }) => G.val);
if (isActive.A) { /* code when effect A is active */ }
if (Object.values(isActive).some(i => i)) { /* code when at least one effect is active */ }
if (Object.values(isActive).every(i => !i)) { /* code when no effects are active */ }
```

---

#### Hold up, wait a minute…

Writing `G = useWatchedState('rollDie', ({ G }) => G)` suddenly made think: Do we even need the getter function at all? Why not just do this?

```js
const { G, ctx } = useEarlyPropsOnEffect('rollDie', 'movePiece', ...);
```

Or if `isActive` is still important:

```js
const [{ G, ctx }, isActive] = useEarlyPropsOnEffect('rollDie', 'movePiece', ...);
```

The rest of my replies are irrelevant if you agree this is a good idea 😂 

---

> The current implementation assumes a pure fonction which only relies on the board props. It's easier to manage dependencies like this. Is it worth changing the signature to allow external deps?

I think it’s probably a good idea to add a dependency array here, yes. As there’s no way to guarantee a function is pure, someone may well try to include external references — perhaps the component has some other state that decides which bit of `G` to watch or something.

> This implementation completely disregards the payload and to be honest it feels a little odd.

I think this is OK — this hook is quite a different model from the others and like you say, with multiple effects (which seems like an important part of this API), also having access to payloads seems like it might be hard to track. In fact, at that point you’d probably want to also provide the effect type to the callback (like the wildcard `'*'` listener) and things get messier than necessary. This hook is designed to give access to the board props at specific times, which is a different concern from the other hooks, so discarding the payload is totally OK.

> I added a new context rather than piggy back on an existing one but that was to keep things tidy, happy to bundle if needed.

This is good I think, as `EffectsContext` is static and `EffectsQueueContext` provides the public queue API.

> Additionally it stores the current props maintained by the plugin rather than the "true" props received by the client (`bgioProps` and not `props`).

I think this is good as you wrote it 👍 

> maybe it would be interesting to store both "old" and "new" props in the context and let the user decide what to get? (and maybe 2 hooks instead of one to choose which one to get?)

I’m not sure I see the case where this would be useful yet. I’d suggest sticking with the current model for now, and if this turns out to be something that is missing, we can always add it later.

**Comment by MathieuLoutre** [comment]
> #### Hold up, wait a minute…

I have to say I'm a little cross I didn't think of that myself... haha 

I looked at all the places I use my own version of the `useWatchedState` and I don't use the `isActive` part at all. I guess the new state is all you need and calling it `useEarlyPropsOnEffect` — though a little verbose — is very descriptive of what this is trying to do, removing the odd feeling I had about the payload: this is purely monitoring effects to update the state in different parts of the application. 

I think that creates a nice distinction between using an effect to signal a state change and using an effect to signal to something temporary to show the user. Also, we don't have to worry about dependencies and that's nice.

As for the name, at the risk of going a little overboard, I might prefer `useLatestPropsOnEffect`? NextProps? NewProps?

One thing to note maybe is the name of the variables received: `const { G, ctx } = ...` is likely to be a little awkward to use in a lot of components already receiving `G` as props. Do we imagine this will replace the usual use of the props being passed down? That seems a rather good idea given how many component need `{ G, ctx }` but I suppose a part of the component might want to depend on `G` passed through props (the "old" `G`) and another part might want to update based on effect?

So would the recommended syntax be `const { G: { objective } } = ...`? (not necessarily a bad thing?)

**Comment by delucis** [comment]
`useLatestPropsOnEffect` seems good to me too.

It’s true that having destructured variables, like `G` etc., could conflict, but that might be a good thing. I would assume it to be less common (and perhaps a bad idea) to use for example `G` passed as a prop as well as this hook. I imagine relying on these two differently timed versions of the same data within one component could get pretty confusing. Doing deeper destructuring like your example, or combining props and hooks will be technically possible, but I would probably recommend keeping the two approaches to accessing this state separate. 

For situations that call for previous or “old” state, using [a `usePrevious` hook](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state) would probably be better than comparing a prop and the hook. And if a component is using both a prop and the hook, perhaps there’s a way to refactor to separate the part that needs the early hook props from the part that just uses the basic props.

(This hook will also be quite versatile, so you could do `useLatestPropsOnEffect('effects:start')` or `useLatestPropsOnEffect('effects:end')` and never need to pass the global props anywhere if you wanted.)

**Comment by MathieuLoutre** [comment]
> And if a component is using both a prop and the hook, perhaps there’s a way to refactor to separate the part that needs the early hook props from the part that just uses the basic props.

Yep, that seems sensible. I've made a new PR with the hook as discussed. Let me know what you think then we can write the docs.

**Pull request closed without merging**
